server:
  port: 8022 # 服务端口
  servlet:
    context-path: /api/blog-service/v1 # 在路径前统一添加前缀
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 数据源配置
      username: test
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://49.235.255.193:3306/blog_data?useUicode=true?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
      # 初始化 最小 最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      maxwait: 360000
      # 配置间隔多久进行一次检查,检测需要关闭的空闲连接,单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小的生存时间,单位是毫秒
      min-evictable-idle-time-millis: 360000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache,并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  jackson:
    # json 序列化排除值为 null 的属性
    default-property-inclusion: non_null
    # 配置 Date 类的时间格式，如果不涉及可以不加
    date-format: yyyy-MM-dd HH:mm:ss
    # 配置 Date 类的时区，如果不涉及可以不加
    time-zone: GMT+8
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
#如果mapper的xml文件没有放在resources目录下，那要配置以下路径
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
  configuration:
    map-underscore-to-camel-case: true # 是否符合下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
